name: skybluecopyworks
favicon: null
layout_spectrum: 0.3311890042386949
typography_spectrum: 0.6504059808794409
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9590558372437954
  lightness: 0.8181267592590302
  saturation: 0.6870861651841551
  rhythmicContrast: 0.10853996756486595
purpose: []
